### PR TITLE
Update Subscription.php

### PR DESCRIPTION
**Pull request by dejanbointsoft**
The quote cron was failing on $quoteItem = $quote->getItemByProduct($product); and it was unable to add the product to quote. 
I'm have assigned the $quoteitem in the time of adding.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi dejanbointsoft,

Sorry for the late responds. We have discussed it and indeed addProduct() function will return the quoteItem so better to use this directly instead of making another call to retrieve it again. I have merged your pull request.

Regards,
Rik
Adyen

**Comment by Maikel-Koek** [comment]
@rikterbeek; I'm not sure, but I think this is done because when a bundle product is added, the latest added simple is returned, instead of the simple product. The bundle that was added, was retrieved by the second line, `$quoteItem = $quote->getItemByProduct($product);`.
So changing this could possibly mess things up..

**Comment by rikterbeek** [comment]
@Maikel-Koek 

You are right with configurable products it is now not going well. so I am going to revert this PR.
@dejanbointsoft we need to find out why this is not working for you or find a better way to do this.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@Maikel-Koek looks like configurable products is not working even in the old situation. I am looking into it.

**Comment by rikterbeek** [comment]
This is the new solution:
https://github.com/Adyen/adyen-magento-subscription/commit/04daf9bbca91f3f43d89682f865068974c61768c

**Pull request merged**
