### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by lfluvisotto**
@rikterbeek little fix in order page, block 'Related Subscription', Schedule Date field.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi @lfluvisotto,

Thanks for the PR. I will look into it one question though does it now not show any value here ?
It is now retrieved from the quote and if that is not needed then we can remove the whole method retrieve the quote for the order.

Regards,
Rik
Adyen

**Comment by lfluvisotto** [comment]
Hello @rikterbeek 

Sorry, I did not understand your question exactly.

For me the datetime of field  'Schedule Date' was not showing.

In line 26 we also could replace:

From > $_subscriptionQuoteAdd = $this->getSubscriptionQuoteAdditionalInfo();

To > $_subscriptionQuoteAdd = $this->getSubscriptionOrderAdditionalInfo();

And keep the line 62 as:
<strong><?php echo $_subscriptionQuoteAdd->getScheduledAtFormatted(); ?></strong>

I think it works that same way.

**Comment by rikterbeek** [comment]
Hi @lfluvisotto ,

Just to be sure the getScheduledAtFormatted is already in the $_subscription variable right so no need to grab additionalData as well i would say. What I mean is if we are doing your change we can remove the following lines because they are not needed: 
https://github.com/lfluvisotto/adyen-magento-subscription/blob/6ddbf6709490c289105b5ce68ccb6b22de0d1940/app/design/adminhtml/default/default/template/adyen_subscription/sales/order/view/subscription.phtml#L26
https://github.com/lfluvisotto/adyen-magento-subscription/blob/6ddbf6709490c289105b5ce68ccb6b22de0d1940/app/design/adminhtml/default/default/template/adyen_subscription/sales/order/view/subscription.phtml#L52

Regards,
Rik
Adyen

**Comment by lfluvisotto** [comment]
Yes, getScheduledAtFormatted is in $_subscription variable/object

$_subscriptionQuoteAdd practically is not necessary.

**Pull request closed without merging**
